name: Deploy to WP Engine production environment
on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: echo "- $GITHUB_WORKSPACE"
    
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_PLUGIN_ACF_KEY: ${{ secrets.PLUGIN_ACF_KEY }}
        file_name: .env
        fail_on_empty: false
        path: /home/runner/work/wpe-deploy-composer-with-env/wpe-deploy-composer-with-env

    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        WPE_ENV: dotenvcomposer
        # Deploy Options
        REMOTE_PATH: "wp-content/"
        FLAGS: -azvr --inplace --delete --include-from config/include.txt --exclude=".*" --exclude-from config/exclude.txt
        PHP_LINT: TRUE
        SCRIPT: wp-content/config/post-deploy.sh
